blank_issues_enabled: false
contact_links:
  - name: Frage zum Projekt
    url: https://github.com/SheylaSam/prisma-capstone/discussions
    about: Diskussionen, offene Fragen, Ideen ohne konkrete Task
