# backend/alembic/versions/0041_agent_audit_trail.py
"""Create agent_audit_trail table for immutable agentic-layer audit log.

Revision ID: 0041
Revises: 0040
Create Date: 2026-06-21

APPEND-ONLY / IMMUTABLE (D-02):
- NO UPDATE, NO DELETE on this table — ever.
- Every new agent run inserts a new row.
- Application layer enforces this: no update() or delete() method on repo.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0041"
down_revision: str | None = "0040"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "agent_audit_trail",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
            comment="UUID primary key; generated by DB (PostgreSQL) or Python uuid4 (SQLite tests)",
        ),
        sa.Column("coin", sa.String(), nullable=False),
        sa.Column("asof", sa.Date(), nullable=False),
        sa.Column(
            "agent_run",
            sa.JSON(),
            nullable=False,
            comment=(
                "Immutable snapshot of full agent run: "
                "{tech_view, onchain_view, senti_view, macro_regime, "
                "bull_case, bear_case, risk_verdict, trade_signal}"
            ),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_agent_audit_trail"),
        comment=(
            "APPEND-ONLY / IMMUTABLE (D-02): "
            "NO UPDATE, NO DELETE on this table. "
            "Each agent run inserts a new row. "
            "No UPDATE/DELETE permission should be granted in production."
        ),
    )


def downgrade() -> None:
    op.drop_table("agent_audit_trail")
