"""SQLAlchemy ORM model for the agent_audit_trail table (append-only / immutable, D-02)."""

from __future__ import annotations

import uuid
from datetime import UTC, date, datetime
from typing import Any

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from backend.infrastructure.persistence.base import Base


class AgentAuditTrailORM(Base):
    """Immutable record of a single agentic-layer agent run.

    APPEND-ONLY (D-02): No UPDATE, no DELETE — ever.
    Each call to the agent pipeline inserts a new row.
    The application-layer repository enforces this by exposing only insert().
    """

    __tablename__ = "agent_audit_trail"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        # PostgreSQL: UUID generated by DB via gen_random_uuid() (see migration 0041).
        # Python / SQLite unit tests: default=uuid.uuid4 generates a UUID before flush.
        default=uuid.uuid4,
        server_default=sa.text("gen_random_uuid()"),
    )
    coin: Mapped[str] = mapped_column(sa.String(), nullable=False)
    asof: Mapped[date] = mapped_column(sa.Date(), nullable=False)
    # sa.JSON() works on both PostgreSQL (as JSON) and SQLite (for unit tests).
    # The Alembic migration (0041) explicitly uses JSONB for PostgreSQL DDL.
    agent_run: Mapped[dict[str, Any]] = mapped_column(sa.JSON(), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
        default=lambda: datetime.now(tz=UTC),
    )
