"""Stub-Implementierung des FundamentalsProvider für Demo und Tests.

Liefert hardcodierte Fundamentaldaten für bekannte Demo-Ticker.
Unbekannte Ticker erhalten leere Daten (alle None).
"""

from backend.domain.models.quality_classic import Fundamentals, UniverseData
from backend.domain.ports.fundamentals_provider import FundamentalsProvider

_DEMO_DATA: dict[str, Fundamentals] = {
    "AAPL": {
        "pe_ratio": 28.0,
        "pb_ratio": 45.0,
        "fcf_yield": 0.038,
        "operating_margin": 0.302,
        "dividend_yield": 0.005,
        "debt_to_equity": 1.76,
        "eps_growth_3y": 0.09,
        "sales_growth_3y": 0.08,
    },
    "MSFT": {
        "pe_ratio": 35.0,
        "pb_ratio": 12.0,
        "fcf_yield": 0.025,
        "operating_margin": 0.425,
        "dividend_yield": 0.007,
        "debt_to_equity": 0.35,
        "eps_growth_3y": 0.15,
        "sales_growth_3y": 0.16,
    },
    "GOOGL": {
        "pe_ratio": 22.0,
        "pb_ratio": 5.5,
        "fcf_yield": 0.042,
        "operating_margin": 0.27,
        "dividend_yield": 0.0,
        "debt_to_equity": 0.06,
        "eps_growth_3y": 0.18,
        "sales_growth_3y": 0.12,
    },
    "NVDA": {
        "pe_ratio": 55.0,
        "pb_ratio": 30.0,
        "fcf_yield": 0.015,
        "operating_margin": 0.55,
        "dividend_yield": 0.001,
        "debt_to_equity": 0.42,
        "eps_growth_3y": 1.20,
        "sales_growth_3y": 0.85,
    },
    "JPM": {
        "pe_ratio": 12.0,
        "pb_ratio": 1.8,
        "fcf_yield": 0.06,
        "operating_margin": 0.35,
        "dividend_yield": 0.025,
        "debt_to_equity": 1.20,
        "eps_growth_3y": 0.08,
        "sales_growth_3y": 0.07,
    },
    "AMZN": {
        "pe_ratio": 42.0,
        "pb_ratio": 8.5,
        "fcf_yield": 0.035,
        "operating_margin": 0.085,
        "dividend_yield": 0.0,
        "debt_to_equity": 0.65,
        "eps_growth_3y": 0.55,
        "sales_growth_3y": 0.18,
    },
    "TSLA": {
        "pe_ratio": 65.0,
        "pb_ratio": 10.0,
        "fcf_yield": 0.012,
        "operating_margin": 0.085,
        "dividend_yield": 0.0,
        "debt_to_equity": 0.10,
        "eps_growth_3y": 0.45,
        "sales_growth_3y": 0.32,
    },
    "META": {
        "pe_ratio": 24.0,
        "pb_ratio": 7.5,
        "fcf_yield": 0.060,
        "operating_margin": 0.34,
        "dividend_yield": 0.005,
        "debt_to_equity": 0.27,
        "eps_growth_3y": 0.45,
        "sales_growth_3y": 0.12,
    },
    "NFLX": {
        "pe_ratio": 42.0,
        "pb_ratio": 9.8,
        "fcf_yield": 0.040,
        "operating_margin": 0.22,
        "dividend_yield": 0.0,
        "debt_to_equity": 0.78,
        "eps_growth_3y": 0.32,
        "sales_growth_3y": 0.10,
    },
    "AMD": {
        "pe_ratio": 48.0,
        "pb_ratio": 4.2,
        "fcf_yield": 0.025,
        "operating_margin": 0.18,
        "dividend_yield": 0.0,
        "debt_to_equity": 0.10,
        "eps_growth_3y": 0.85,
        "sales_growth_3y": 0.55,
    },
    "INTC": {
        "pe_ratio": 18.0,
        "pb_ratio": 1.3,
        "fcf_yield": -0.02,
        "operating_margin": 0.06,
        "dividend_yield": 0.012,
        "debt_to_equity": 0.45,
        "eps_growth_3y": -0.25,
        "sales_growth_3y": -0.08,
    },
    "ORCL": {
        "pe_ratio": 28.0,
        "pb_ratio": 38.0,
        "fcf_yield": 0.050,
        "operating_margin": 0.30,
        "dividend_yield": 0.013,
        "debt_to_equity": 4.5,
        "eps_growth_3y": 0.07,
        "sales_growth_3y": 0.06,
    },
    "CRM": {
        "pe_ratio": 48.0,
        "pb_ratio": 4.5,
        "fcf_yield": 0.045,
        "operating_margin": 0.21,
        "dividend_yield": 0.001,
        "debt_to_equity": 0.16,
        "eps_growth_3y": 0.95,
        "sales_growth_3y": 0.18,
    },
    # --- SMI-20 (Swiss Market Index, siehe scripts/seed_smi_universe.py) ---
    "NESN": {
        "pe_ratio": 19.5,
        "pb_ratio": 5.2,
        "fcf_yield": 0.045,
        "operating_margin": 0.17,
        "dividend_yield": 0.031,
        "debt_to_equity": 0.65,
        "eps_growth_3y": 0.04,
        "sales_growth_3y": 0.03,
    },
    "NOVN": {
        "pe_ratio": 17.0,
        "pb_ratio": 4.0,
        "fcf_yield": 0.055,
        "operating_margin": 0.30,
        "dividend_yield": 0.034,
        "debt_to_equity": 0.45,
        "eps_growth_3y": 0.07,
        "sales_growth_3y": 0.05,
    },
    "ROG": {
        "pe_ratio": 16.0,
        "pb_ratio": 6.5,
        "fcf_yield": 0.060,
        "operating_margin": 0.28,
        "dividend_yield": 0.038,
        "debt_to_equity": 0.55,
        "eps_growth_3y": 0.02,
        "sales_growth_3y": 0.01,
    },
    "ABBN": {
        "pe_ratio": 24.0,
        "pb_ratio": 6.0,
        "fcf_yield": 0.040,
        "operating_margin": 0.16,
        "dividend_yield": 0.022,
        "debt_to_equity": 0.40,
        "eps_growth_3y": 0.09,
        "sales_growth_3y": 0.06,
    },
    "ZURN": {
        "pe_ratio": 14.0,
        "pb_ratio": 7.5,
        "fcf_yield": 0.065,
        "operating_margin": 0.12,
        "dividend_yield": 0.055,
        "debt_to_equity": 0.30,
        "eps_growth_3y": 0.06,
        "sales_growth_3y": 0.04,
    },
    "UBSG": {
        "pe_ratio": 11.0,
        "pb_ratio": 1.1,
        "fcf_yield": 0.070,
        "operating_margin": 0.25,
        "dividend_yield": 0.035,
        "debt_to_equity": 2.20,
        "eps_growth_3y": 0.10,
        "sales_growth_3y": 0.05,
    },
    "UHR": {
        "pe_ratio": 20.0,
        "pb_ratio": 2.0,
        "fcf_yield": 0.035,
        "operating_margin": 0.10,
        "dividend_yield": 0.020,
        "debt_to_equity": 0.15,
        "eps_growth_3y": -0.05,
        "sales_growth_3y": -0.03,
    },
    "GEBN": {
        "pe_ratio": 30.0,
        "pb_ratio": 9.0,
        "fcf_yield": 0.030,
        "operating_margin": 0.24,
        "dividend_yield": 0.024,
        "debt_to_equity": 0.35,
        "eps_growth_3y": 0.05,
        "sales_growth_3y": 0.04,
    },
    "GIVN": {
        "pe_ratio": 32.0,
        "pb_ratio": 6.8,
        "fcf_yield": 0.028,
        "operating_margin": 0.21,
        "dividend_yield": 0.018,
        "debt_to_equity": 0.50,
        "eps_growth_3y": 0.06,
        "sales_growth_3y": 0.05,
    },
    "LONN": {
        "pe_ratio": 28.0,
        "pb_ratio": 4.5,
        "fcf_yield": 0.020,
        "operating_margin": 0.22,
        "dividend_yield": 0.012,
        "debt_to_equity": 0.60,
        "eps_growth_3y": 0.08,
        "sales_growth_3y": 0.07,
    },
    "SREN": {
        "pe_ratio": 10.0,
        "pb_ratio": 1.3,
        "fcf_yield": 0.080,
        "operating_margin": 0.14,
        "dividend_yield": 0.060,
        "debt_to_equity": 0.35,
        "eps_growth_3y": 0.12,
        "sales_growth_3y": 0.06,
    },
    "SGKN": {
        "pe_ratio": 26.0,
        "pb_ratio": 8.0,
        "fcf_yield": 0.038,
        "operating_margin": 0.15,
        "dividend_yield": 0.028,
        "debt_to_equity": 0.55,
        "eps_growth_3y": 0.04,
        "sales_growth_3y": 0.03,
    },
    "SLHN": {
        "pe_ratio": 13.0,
        "pb_ratio": 1.6,
        "fcf_yield": 0.075,
        "operating_margin": 0.11,
        "dividend_yield": 0.050,
        "debt_to_equity": 0.40,
        "eps_growth_3y": 0.07,
        "sales_growth_3y": 0.05,
    },
    "SCMN": {
        "pe_ratio": 15.0,
        "pb_ratio": 4.8,
        "fcf_yield": 0.058,
        "operating_margin": 0.20,
        "dividend_yield": 0.048,
        "debt_to_equity": 1.10,
        "eps_growth_3y": 0.01,
        "sales_growth_3y": 0.01,
    },
    "SIKA": {
        "pe_ratio": 34.0,
        "pb_ratio": 5.5,
        "fcf_yield": 0.026,
        "operating_margin": 0.15,
        "dividend_yield": 0.009,
        "debt_to_equity": 0.70,
        "eps_growth_3y": 0.11,
        "sales_growth_3y": 0.09,
    },
    "HOLN": {
        "pe_ratio": 12.0,
        "pb_ratio": 1.9,
        "fcf_yield": 0.072,
        "operating_margin": 0.18,
        "dividend_yield": 0.040,
        "debt_to_equity": 0.65,
        "eps_growth_3y": 0.06,
        "sales_growth_3y": 0.04,
    },
    "PGHN": {
        "pe_ratio": 22.0,
        "pb_ratio": 5.0,
        "fcf_yield": 0.042,
        "operating_margin": 0.45,
        "dividend_yield": 0.045,
        "debt_to_equity": 0.20,
        "eps_growth_3y": 0.03,
        "sales_growth_3y": 0.02,
    },
    "KNIN": {
        "pe_ratio": 18.0,
        "pb_ratio": 5.8,
        "fcf_yield": 0.050,
        "operating_margin": 0.07,
        "dividend_yield": 0.036,
        "debt_to_equity": 0.25,
        "eps_growth_3y": 0.04,
        "sales_growth_3y": 0.03,
    },
    "CFR": {
        "pe_ratio": 23.0,
        "pb_ratio": 3.2,
        "fcf_yield": 0.044,
        "operating_margin": 0.19,
        "dividend_yield": 0.021,
        "debt_to_equity": 0.10,
        "eps_growth_3y": 0.05,
        "sales_growth_3y": 0.04,
    },
    "STMN": {
        "pe_ratio": 36.0,
        "pb_ratio": 7.2,
        "fcf_yield": 0.024,
        "operating_margin": 0.20,
        "dividend_yield": 0.008,
        "debt_to_equity": 0.05,
        "eps_growth_3y": 0.10,
        "sales_growth_3y": 0.08,
    },
}

_EMPTY: Fundamentals = {
    "pe_ratio": None,
    "pb_ratio": None,
    "fcf_yield": None,
    "operating_margin": None,
    "dividend_yield": None,
    "debt_to_equity": None,
    "eps_growth_3y": None,
    "sales_growth_3y": None,
}


class StubFundamentalsProvider(FundamentalsProvider):
    async def get_fundamentals(self, tickers: list[str]) -> UniverseData:
        return {t: _DEMO_DATA.get(t, dict(_EMPTY)) for t in tickers}
